name: 'x15stack-azure-diagrams-generator'
description: 'Runs AzureDiagramGenerator'
branding:
  icon: 'command'
  color: 'green'
inputs:
  subscriptionId:
    description: 'Azure Subscription Id'
    required: true
  resourceGroup:
    description: 'Azure Resource Group to match on. Regexes supported. Also * can be used as a simple non greedy wildcard (he*o) will match a resource group called hello'
    required: true
  accessToken:
    description: 'Access Token that can read the resources'
    required: true
  condensed:
    description: 'Collapse private endpoints / vm disks to produce a simple view. Useful for large architectures'
    required: true
    default: 'true'
  inferConnections:
    description: 'Look into configuration settings to infer more links between resources. Can clutter large architectures'
    required: true
    default: 'true'
  outputFileName:
    description: 'Output file name to write to (will write to the working directory)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--subscription-id" 
    - "${{ inputs.subscriptionId }}"
    - "--resource-group"
    - "${{ inputs.resourceGroup }}"
    - "--token"
    - "${{ inputs.accessToken }}"
    - "--output-file-name"
    - "${{ inputs.outputFileName }}"
    - "--condensed"
    - "${{  inputs.condensed}}"
    - "--no-infer"
    - "${{  !inputs.inferConnections }}"
