name: BuildAndPackage

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package-app:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Pack Nuget
        run: dotnet pack AzureDiagramGenerator/AzureDiagramGenerator.csproj -p:Version=${{ steps.gitversion.outputs.NuGetVersionV2 }} --output ./publish/

      - name: Publish to Nuget
        run: dotnet nuget push ./publish/AzureDiagramGenerator.${{ steps.gitversion.outputs.NuGetVersionV2 }}.nupkg  --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
    outputs:
      version: ${{ steps.gitversion.outputs.NuGetVersionV2 }}

  build-and-publish-docker-container:
    needs: build-and-package-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          VERSION: ${{ needs.build-and-package-app.outputs.version }}
        with:
          context: .
          push: true
          tags: |
            ghcr.io/graemefoster/azurediagrams:latest
            ghcr.io/graemefoster/azurediagrams:${{ needs.build-and-package-app.outputs.version }}
