name: BuildAndPackage

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish-docker-container:
    needs: build-and-package-app
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ needs.build-and-package-app.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: NUGET_VERSION=${{ steps.gitversion.outputs.NuGetVersionV2 }}
          tags: |
            ghcr.io/graemefoster/azurediagrams:latest
            ghcr.io/graemefoster/azurediagrams:${{ steps.gitversion.outputs.NuGetVersionV2 }}
