name: BuildAndPackage

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-test-diagram:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: graemefoster-azurediagrams-action
        uses: graemefoster/AzureResourceMap@v0.5.1
        with:
          subscriptionId: ${{ secrets.SUSCRIPTION_ID }}
          resourceGroup: graemefosterdns
        